version: 2
updates:
  - package-ecosystem: pip
    directories:
      - "/functions/hello/"
      - "/functions/host-details/"
      - "/functions/host-info/"
      - "/functions/log-event/"
      - "/functions/servicenow/"
      - "/functions/user-management/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "actions/setup-node"
        versions: [">=6.2.0"]
      - dependency-name: "actions/setup-python"
        versions: [">=6.1.0"]
